########################################
# Messages
########################################
float64 leftStickY
float64 leftStickX
float64 rightStickY
float64 rightStickX
float64 axisL2
float64 axisR2

int16 arrowsX
int16 arrowsY
int16 buttonSq
int16 buttonX
int16 buttonO
int16 buttonTr
int16 l1
int16 r1
int16 l2
int16 r2
int16 buttonShare
int16 buttonOption
int16 buttonTouch
int16 yawturn
int16 buttonCenter
int16 buttonLeftJoy
int16 buttonRightJoy
